### ISSUE TITLE
Abb *generaArbol(Abb *ptrArbol, i, j);

### ISSUE THREAD

**Issue by conyperez** [IC-ULS/edd-taller2-g3#32]

**Comment by Blaudio** [comment]
Aqui tengo un codigo que se podria usar para el recorrido del arbol, me gustaria saber su opinion acerca de el:

void recorreCalabozo(Arbol *arbol, char direccion){
	int existe;
	if(direccion== "N"){
		existe=buscaNorte(arbol);
		if(existe==1){
			//el nodo norte es el padre
			return(arbol->padre);
		}
		if(existe==2){
			//el nodo norte es el hijo uno
			return(arbol->hijoUno);
		}
		if(existe==3){
			//el nodo norte es el hijo dos
			return(arbol->hijoDos);
		}
		if(existe==4){
			//el nodo norte es el hijo tres
			return(arbol->hijoTres);
		}
		//no tiene acceso al norte
	}else if (direccion == "S"){
		existe=buscaSur(arbol);
		if(existe==1){
			//el nodo sur es el padre
			return(arbol->padre);
		}
		if(existe==2){
			//el nodo sur es el hijo uno
			return(arbol->hijoUno);
		}
		if(existe==3){
			//el nodo sur es el hijo dos
			return(arbol->hijoDos);
		}
		if(existe==4){
			//el nodo sur es el hijo tres
			return(arbol->hijoTres);
		}
		//no tiene acceso al sur
	}else if (dirrecion == "O"){
		existe=buscaOeste(arbol);
		if(existe==1){
			//el nodo oeste es el padre
			return(arbol->padre);
		}
		if(existe==2){
			//el nodo oeste es el hijo uno
			return(arbol->hijoUno);
		}
		if(existe==3){
			//el nodo oeste es el hijo dos
			return(arbol->hijoDos);
		}
		if(existe==4){
			//el nodo oeste es el hijo tres
			return(arbol->hijoTres);
		}
		//no tiene acceso al oeste
	}else if (direccion == "E"){
		existe=buscaEste(arbol);
		if(existe==1){
			//el nodo este es el padre
			return(arbol->padre);
		}
		if(existe==2){
			//el nodo este es el hijo uno
			return(arbol->hijoUno);
		}
		if(existe==3){
			//el nodo este es el hijo dos
			return(arbol->hijoDos);
		}
		if(existe==4){
			//el nodo este es el hijo tres
			return(arbol->hijoTres);
		}
		//no tiene acceso al este
	}
	//si llegamos a esta parte es por que no se puede acceder a la direccion solicitada por diversas razones
}

Arbol buscaNorte(Arbol *arbol){
	//comprueba Si el norte existe en algun nodo del arbol ya existente
	if(arbol->padre!=NULL && arbol->padre->dato->posicion_y < arbol->dato->posicion_y){
		return (1);
	}else if(arbol->hijoUno!=NULL && arbol->hijoUno->dato->posicion_y < arbol->dato->posicion_y){
		return (2);
	}else if(arbol->hijoDos!=NULL && arbol->hijoDos->dato->posicion_y < arbol->dato->posicion_y){
		return (3);
	}else if(arbol->hijoTres!=NULL && arbol->hijoTres->dato->posicion_y < arbol->dato->posicion_y){
		return (4);
	}
	return (NULL);
}

Arbol buscaSur(Arbol *arbol){
	//comprueba Si el sur existe en algun nodo del arbol ya existente
	if(arbol->padre!=NULL && arbol->padre->dato->posicion_y > arbol->dato->posicion_y){
		return (1);
	}else if(arbol->hijoUno!=NULL && arbol->hijoUno->dato->posicion_y > arbol->dato->posicion_y){
		return (2);
	}else if(arbol->hijoDos!=NULL && arbol->hijoDos->dato->posicion_y > arbol->dato->posicion_y){
		return (3);
	}else if(arbol->hijoTres!=NULL && arbol->hijoTres->dato->posicion_y > arbol->dato->posicion_y){
		return (4);
	}
	return (NULL);
}

Arbol buscaOeste(Arbol *arbol){
	//comprueba Si el oeste existe en algun nodo del arbol ya existente
	if(arbol->padre!=NULL && arbol->padre->dato->posicion_x < arbol->dato->posicion_x){
		return (1);
	}else if(arbol->hijoUno!=NULL && arbol->hijoUno->dato->posicion_x < arbol->dato->posicion_x){
		return (2);
	}else if(arbol->hijoDos!=NULL && arbol->hijoDos->dato->posicion_x < arbol->dato->posicion_x){
		return (3);
	}else if(arbol->hijoTres!=NULL && arbol->hijoTres->dato->posicion_x < arbol->dato->posicion_x){
		return (4);
	}
	return (NULL);
}

Arbol buscaEste(Arbol *arbol){
	//comprueba Si el este existe en algun nodo del arbol ya existente
	if(arbol->padre!=NULL && arbol->padre->dato->posicion_x > arbol->dato->posicion_x){
		return (1);
	}else if(arbol->hijoUno!=NULL && arbol->hijoUno->dato->posicion_x > arbol->dato->posicion_x){
		return (2);
	}else if(arbol->hijoDos!=NULL && arbol->hijoDos->dato->posicion_x > arbol->dato->posicion_x){
		return (3);
	}else if(arbol->hijoTres!=NULL && arbol->hijoTres->dato->posicion_x > arbol->dato->posicion_x){
		return (4);
	}
	return (NULL);
}
